### PR TITLE
feat: Upgrade chart to latest version

### LINKED ISSUE #8: External-DNS is pinned to old version
See https://github.com/lablabs/terraform-aws-eks-external-dns/blob/master/templates/values.yaml.tpl#L49-L52

It should either be configurable via terraform variable or just use the default of the helm-chart version.

### PR DESCRIPTION
**Pull request by toabi**
This would fix #8

### CODE REVIEW

**Comment by toabi** [comment]
Actually I noticed that the deployments before didn't respect the interval of 30 seconds and updated every second.

After two deployments in different AWS Accounts, we quickly hit the 5req/sec Rate Limit :D

**Comment by adys** [comment]
@toabi could you describe what you mean exactly? How did you hit the 5req/sec route53 limit?

**Comment by toabi** [comment]
Well, external-dns checked the zone state every second…

**Comment by adys** [comment]
Is that a bug in the new external-dns version which is deployed by the bitnami chart?

**Comment by toabi** [comment]
It was a bug in the old one, using the one in this PR fixed the issue for me.

**Comment by adys** [comment]
Great! The pipeline is failing because you haven't executed pre-commit which generates the README doc. We've added some notes about this. Please check https://github.com/lablabs/terraform-aws-eks-external-dns#validation-linters-and-pull-requests. If the instrustions are not clear, let us know.

**Comment by toabi** [comment]
Finally installed this pre-commit thingy. Nice setup there. This would be now ready-to-merge.

**Comment by adys** [comment]
@toabi we are planning to integrate the terraform-docs and fmt into the CI pipeline and commit the changes automatically. Thanks for updating it. The changes look good to me.

**Pull request merged**
